import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitVidaRider1719900000000 implements MigrationInterface {
  name = 'InitVidaRider1719900000000';
  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto"`);
    await q.query(`CREATE TABLE riders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mobile VARCHAR(15) NOT NULL UNIQUE, name VARCHAR(100), date_of_birth DATE, gender VARCHAR(10) CHECK (gender IN ('male','female','other')), city VARCHAR(50), vehicle_type VARCHAR(20) DEFAULT 'bike' CHECK (vehicle_type IN ('bike','scooter','cargo_bike')), max_parcel_weight_kg DECIMAL(5,2) DEFAULT 10.0, onboarding_status VARCHAR(50) NOT NULL DEFAULT 'registered', rating DECIMAL(3,2) DEFAULT 0.00, total_deliveries INT DEFAULT 0, total_ratings INT DEFAULT 0, acceptance_rate DECIMAL(5,2) DEFAULT 100.00, cancellation_score INT DEFAULT 0, activated_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE otp_requests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mobile VARCHAR(15) NOT NULL, otp_hash VARCHAR(255) NOT NULL, attempts INT DEFAULT 0, is_verified BOOLEAN DEFAULT FALSE, locked_until TIMESTAMP, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE rider_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rider_id UUID NOT NULL REFERENCES riders(id) ON DELETE CASCADE, document_type VARCHAR(30) NOT NULL CHECK (document_type IN ('driving_license','vehicle_rc','aadhaar','pan')), file_url VARCHAR(500) NOT NULL, file_name VARCHAR(255), file_size_bytes INT, mime_type VARCHAR(50), upload_status VARCHAR(20) DEFAULT 'accepted', verification_status VARCHAR(20) DEFAULT 'pending' CHECK (verification_status IN ('pending','verified','failed')), failure_reason VARCHAR(255), verified_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW(), UNIQUE(rider_id, document_type))`);
    await q.query(`CREATE TABLE background_checks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rider_id UUID NOT NULL REFERENCES riders(id), status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','cleared','flagged','inconclusive')), provider_reference VARCHAR(100), result_details JSONB, initiated_at TIMESTAMP DEFAULT NOW(), completed_at TIMESTAMP)`);
    await q.query(`CREATE TABLE training_progress (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rider_id UUID NOT NULL REFERENCES riders(id), module_id VARCHAR(50) NOT NULL, status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','in_progress','completed')), completed_at TIMESTAMP, UNIQUE(rider_id, module_id))`);
    await q.query(`CREATE TABLE quiz_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rider_id UUID NOT NULL REFERENCES riders(id), answers JSONB NOT NULL, score INT NOT NULL, total_questions INT DEFAULT 10, passed BOOLEAN NOT NULL, attempted_at TIMESTAMP DEFAULT NOW())`);
    await q.query(`CREATE TABLE quiz_questions (id SERIAL PRIMARY KEY, question TEXT NOT NULL, options JSONB NOT NULL, correct_option INT NOT NULL, explanation TEXT, is_active BOOLEAN DEFAULT TRUE)`);
    await q.query(`CREATE TABLE bank_accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rider_id UUID NOT NULL REFERENCES riders(id), account_holder_name VARCHAR(100) NOT NULL, account_number_encrypted VARCHAR(500) NOT NULL, account_number_masked VARCHAR(20) NOT NULL, ifsc_code VARCHAR(11) NOT NULL, upi_id VARCHAR(100), verification_status VARCHAR(20) DEFAULT 'pending' CHECK (verification_status IN ('pending','verified','failed')), verified_at TIMESTAMP, is_primary BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT NOW())`);
    await q.query(`CREATE TABLE order_dispatches (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id VARCHAR(50) NOT NULL UNIQUE, status VARCHAR(30) NOT NULL DEFAULT 'searching', phase SMALLINT DEFAULT 1, city VARCHAR(50) NOT NULL, pickup_lat DECIMAL(10,7) NOT NULL, pickup_lng DECIMAL(10,7) NOT NULL, pickup_address VARCHAR(255), pickup_contact_name VARCHAR(100), pickup_contact_phone VARCHAR(15), dropoff_lat DECIMAL(10,7) NOT NULL, dropoff_lng DECIMAL(10,7) NOT NULL, dropoff_address VARCHAR(255), dropoff_contact_name VARCHAR(100), dropoff_contact_phone VARCHAR(15), customer_id VARCHAR(50), parcel_weight_kg DECIMAL(5,2) DEFAULT 2.0, requires_heavy_vehicle BOOLEAN DEFAULT FALSE, special_notes TEXT, assigned_rider_id UUID REFERENCES riders(id), redispatch_count SMALLINT DEFAULT 0, riders_offered_count INT DEFAULT 0, riders_rejected_count INT DEFAULT 0, distance_km DECIMAL(6,2), estimated_earnings INT, started_at TIMESTAMP DEFAULT NOW(), assigned_at TIMESTAMP, en_route_at TIMESTAMP, arrived_pickup_at TIMESTAMP, picked_up_at TIMESTAMP, in_transit_at TIMESTAMP, delivered_at TIMESTAMP, cancelled_at TIMESTAMP)`);
    await q.query(`CREATE TABLE dispatch_offers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), dispatch_id UUID NOT NULL REFERENCES order_dispatches(id), order_id VARCHAR(50) NOT NULL, rider_id UUID NOT NULL REFERENCES riders(id), status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','timeout','cancelled')), phase SMALLINT NOT NULL, distance_km DECIMAL(6,2), estimated_earnings INT, timeout_seconds INT DEFAULT 30, reason VARCHAR(50), offered_at TIMESTAMP DEFAULT NOW(), responded_at TIMESTAMP, expires_at TIMESTAMP NOT NULL)`);
    await q.query(`CREATE TABLE dispatch_events (id BIGSERIAL PRIMARY KEY, dispatch_id UUID NOT NULL REFERENCES order_dispatches(id), order_id VARCHAR(50) NOT NULL, event_type VARCHAR(50) NOT NULL, rider_id UUID, phase SMALLINT, details JSONB, created_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE rider_earnings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rider_id UUID NOT NULL REFERENCES riders(id), order_id VARCHAR(50) NOT NULL, dispatch_id UUID REFERENCES order_dispatches(id), earning_type VARCHAR(30) DEFAULT 'delivery' CHECK (earning_type IN ('delivery','cancellation_compensation','bonus','tip')), base_fare INT NOT NULL DEFAULT 0, distance_bonus INT DEFAULT 0, surge_bonus INT DEFAULT 0, tip INT DEFAULT 0, total INT NOT NULL, distance_km DECIMAL(6,2), duration_minutes INT, earned_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE rider_locations (id BIGSERIAL PRIMARY KEY, rider_id UUID NOT NULL, lat DECIMAL(10,7) NOT NULL, lng DECIMAL(10,7) NOT NULL, speed DECIMAL(5,1), bearing DECIMAL(5,1), recorded_at TIMESTAMP DEFAULT NOW())`);
    await q.query(`CREATE TABLE onboarding_events (id BIGSERIAL PRIMARY KEY, rider_id UUID NOT NULL REFERENCES riders(id), event_type VARCHAR(50) NOT NULL, from_status VARCHAR(50), to_status VARCHAR(50), details JSONB, created_at TIMESTAMP DEFAULT NOW())`);
  }
  async down(q: QueryRunner): Promise<void> {
    for (const table of ['onboarding_events','rider_locations','rider_earnings','dispatch_events','dispatch_offers','order_dispatches','bank_accounts','quiz_questions','quiz_attempts','training_progress','background_checks','rider_documents','otp_requests','riders']) {
      await q.query(`DROP TABLE IF EXISTS ${table} CASCADE`);
    }
  }
}
