import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddCustomerWalletOrders1720000000000 implements MigrationInterface {
  name = 'AddCustomerWalletOrders1720000000000';

  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TABLE customers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mobile VARCHAR(15) NOT NULL UNIQUE, name VARCHAR(100), email VARCHAR(255), is_verified BOOLEAN DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE customer_otp_requests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mobile VARCHAR(15) NOT NULL, otp_hash VARCHAR(255) NOT NULL, attempts INT DEFAULT 0, is_verified BOOLEAN DEFAULT FALSE, locked_until TIMESTAMP, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE wallets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID NOT NULL REFERENCES customers(id) UNIQUE, currency_code VARCHAR(3) DEFAULT 'INR', cached_balance INT NOT NULL DEFAULT 0 CHECK (cached_balance >= 0), available_balance INT NOT NULL DEFAULT 0 CHECK (available_balance >= 0), status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'frozen', 'closed')), version INT NOT NULL DEFAULT 0, daily_topup_limit INT DEFAULT 1000000, monthly_topup_limit INT DEFAULT 10000000, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE payment_transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), wallet_id UUID NOT NULL REFERENCES wallets(id), amount INT NOT NULL, currency_code VARCHAR(3) DEFAULT 'INR', status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'captured', 'failed', 'refunded')), gateway_provider VARCHAR(20) DEFAULT 'razorpay', gateway_order_id VARCHAR(100), gateway_payment_id VARCHAR(100), payment_method VARCHAR(30), idempotency_key VARCHAR(64) NOT NULL UNIQUE, metadata JSONB, initiated_at TIMESTAMP DEFAULT NOW(), captured_at TIMESTAMP, expires_at TIMESTAMP)`);
    await q.query(`CREATE TABLE wallet_transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), wallet_id UUID NOT NULL REFERENCES wallets(id), txn_type VARCHAR(10) NOT NULL CHECK (txn_type IN ('credit', 'debit')), txn_category VARCHAR(30) NOT NULL CHECK (txn_category IN ('topup', 'order_payment', 'hold_capture', 'refund', 'cancellation_fee', 'bonus')), amount INT NOT NULL, running_balance INT NOT NULL, description VARCHAR(255), status VARCHAR(20) DEFAULT 'completed', reference_type VARCHAR(30), reference_id VARCHAR(100), created_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE wallet_holds (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), wallet_id UUID NOT NULL REFERENCES wallets(id), amount INT NOT NULL, reason VARCHAR(255), reference_type VARCHAR(30), reference_id VARCHAR(100), status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'captured', 'released', 'expired')), idempotency_key VARCHAR(64) NOT NULL UNIQUE, capture_txn_id UUID REFERENCES wallet_transactions(id), created_at TIMESTAMP NOT NULL DEFAULT NOW(), expires_at TIMESTAMP NOT NULL, captured_at TIMESTAMP, released_at TIMESTAMP)`);
    await q.query(`CREATE TABLE topup_limits_tracker (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), wallet_id UUID NOT NULL REFERENCES wallets(id), period_type VARCHAR(10) NOT NULL CHECK (period_type IN ('daily', 'monthly')), period_start DATE NOT NULL, amount_used INT NOT NULL DEFAULT 0, UNIQUE(wallet_id, period_type, period_start))`);
    await q.query(`CREATE TABLE orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id VARCHAR(50) NOT NULL UNIQUE, customer_id UUID NOT NULL REFERENCES customers(id), status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'payment_pending', 'confirmed', 'searching', 'assigned', 'en_route_pickup', 'arrived_pickup', 'picked_up', 'in_transit', 'delivered', 'cancelled')), pickup_lat DECIMAL(10,7) NOT NULL, pickup_lng DECIMAL(10,7) NOT NULL, pickup_address VARCHAR(255) NOT NULL, pickup_contact_name VARCHAR(100), pickup_contact_phone VARCHAR(15), dropoff_lat DECIMAL(10,7) NOT NULL, dropoff_lng DECIMAL(10,7) NOT NULL, dropoff_address VARCHAR(255) NOT NULL, dropoff_contact_name VARCHAR(100) NOT NULL, dropoff_contact_phone VARCHAR(15) NOT NULL, parcel_weight_kg DECIMAL(5,2) DEFAULT 1.0, special_notes TEXT, distance_km DECIMAL(6,2), base_fare INT NOT NULL, distance_fare INT NOT NULL, weight_surcharge INT DEFAULT 0, platform_fee INT DEFAULT 500, total_amount INT NOT NULL, payment_method VARCHAR(20) DEFAULT 'wallet' CHECK (payment_method IN ('wallet', 'cash', 'online')), payment_status VARCHAR(30) DEFAULT 'pending', payment_reference_id VARCHAR(100), hold_id UUID REFERENCES wallet_holds(id), cancellation_fee INT DEFAULT 0, assigned_rider_id UUID, rider_name VARCHAR(100), rider_phone_masked VARCHAR(15), rider_vehicle_type VARCHAR(20), rider_rating DECIMAL(3,2), estimated_delivery_minutes INT, confirmed_at TIMESTAMP, assigned_at TIMESTAMP, picked_up_at TIMESTAMP, delivered_at TIMESTAMP, cancelled_at TIMESTAMP, cancel_reason VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE order_events (id BIGSERIAL PRIMARY KEY, order_id VARCHAR(50) NOT NULL, event_type VARCHAR(50) NOT NULL, title VARCHAR(100) NOT NULL, description VARCHAR(255), details JSONB, created_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE order_ratings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id VARCHAR(50) NOT NULL UNIQUE, customer_id UUID NOT NULL REFERENCES customers(id), rider_id UUID, delivery_rating INT NOT NULL CHECK (delivery_rating BETWEEN 1 AND 5), rider_rating INT NOT NULL CHECK (rider_rating BETWEEN 1 AND 5), comments TEXT, created_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE TABLE saved_addresses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID NOT NULL REFERENCES customers(id), label VARCHAR(50) NOT NULL, address VARCHAR(255) NOT NULL, lat DECIMAL(10,7) NOT NULL, lng DECIMAL(10,7) NOT NULL, contact_name VARCHAR(100), contact_phone VARCHAR(15), is_default BOOLEAN DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT NOW())`);
    await q.query(`CREATE INDEX idx_customers_mobile ON customers(mobile)`);
    await q.query(`CREATE INDEX idx_wallets_customer ON wallets(customer_id)`);
    await q.query(`CREATE INDEX idx_payment_txn_wallet ON payment_transactions(wallet_id)`);
    await q.query(`CREATE INDEX idx_wallet_txn_wallet ON wallet_transactions(wallet_id, created_at DESC)`);
    await q.query(`CREATE INDEX idx_holds_wallet ON wallet_holds(wallet_id, status)`);
    await q.query(`CREATE INDEX idx_orders_customer ON orders(customer_id, created_at DESC)`);
    await q.query(`CREATE INDEX idx_orders_status ON orders(status)`);
    await q.query(`CREATE INDEX idx_order_events ON order_events(order_id)`);
    await q.query(`CREATE INDEX idx_saved_addr ON saved_addresses(customer_id)`);
  }

  async down(q: QueryRunner): Promise<void> {
    for (const table of ['saved_addresses', 'order_ratings', 'order_events', 'orders', 'topup_limits_tracker', 'wallet_holds', 'wallet_transactions', 'payment_transactions', 'wallets', 'customer_otp_requests', 'customers']) {
      await q.query(`DROP TABLE IF EXISTS ${table} CASCADE`);
    }
  }
}
